### ISSUE TITLE
(Spike) Investigate solution for embedding components in docs site

### ISSUE THREAD

**Issue by k9dh3zij** [defencedigital/design-system-docs#16]
A spike to investigate a solution for embedding live components directly from a design tool into the docs site, avoiding the need to export multiple flat PNGs first. 

Why: The current docs site requires static images to display a component's overview, anatomy, states etc.
This creates a significant overhead as well as potential discrepancies every time there is an update to a component.

Potential solution 1: If we use Axure html/css/js prototypes, can we embed directly from Axure as an iFrame in the docs site?

Potential solution 2: Can we embed live components from Storybook, and use PNGs where these are not enough? This means more work to export PNGs from Axure.

**Comment by k9dh3zij** [comment]
Need to check with @m7kvqbe1 and @hxltrhuxze for a viable long-term approach to this.

**Comment by jpveooys** [comment]
Outcome of the spike was to go with embedding Storybook stories in iframes (using https://github.com/davidjbradshaw/iframe-resizer-react) (and supplementing with images if needed).

(See also https://github.com/defencedigital/mod-uk-design-system/issues/3058 for speeding up loading of stories.)
